---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by knia.
--- DateTime: 2019/3/7 18:18
---
---说明：用于在输出时替换为正确的名字
---
---
module('Ex_skill_alter_names', package.seeall)

ex_skill_alter_names = {
    ["流星群"] = "直觉",
    ["吞食魔蛇"] = "吞噬魔蛇",
    ["90帝隆"] = "炎爆拳",
    ["无双战技"] = "武神裁决",
    ["斩首连击"] = "断罪连击",
    ["圣夜"] = "圣月夜",
    ["魔音"] = "神曲二重奏",
    ["90格莱明"] = "濒死反击",
    ["魔王的施舍"] = "强欲",
}