---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by knia.
--- DateTime: 2019/3/8 19:47
---
module("getComboList",package.seeall)

function getSkillNames(value)
    local skill_ids = {}
    local skill_names = {}
    if value.skill_1 or value.skill_2 then
        skill_ids[1] = value.skill_1
        skill_ids[2] = value.skill_2
        skill_ids[3] = value.skill_3
        skill_names[1] =XML_skill.skills[skill_ids[1]].skill_name
        skill_names[2] =XML_skill.skills[skill_ids[2]].skill_name
        if skill_ids[3] then
            skill_names[3] =XML_skill.skills[skill_ids[3]].skill_name
        else
            skill_names[3] = ""
        end
    elseif value.group_skill_1 or value.group_skill_2 then
        skill_ids[1] = value.group_skill_1
        skill_ids[2] = value.group_skill_2
        skill_ids[3] = value.group_skill_3
        skill_names[1] =XML_skill.skillgroup[skill_ids[1]].name
        skill_names[2] =XML_skill.skillgroup[skill_ids[2]].name
        if skill_ids[3] then
            skill_names[3] =XML_skill.skillgroup[skill_ids[3]].name
        else
            skill_names[3] = ""
        end
    end
    return skill_names
end



--运行获得组合技表
function runGetCombo()

    local combo_id
    local combo_name
    local combo_desc
    local skill_names_table
    for k, v in pairs(XML_skill.combo) do
        combo_id = k
        combo_name = v.name
        combo_desc = v.combo_effect

        if combo_name == nil then
            combo_name = combo_desc
        end

        skill_names_table = getSkillNames(v)
        print(k..","..combo_name..","..combo_desc..","..skill_names_table[1]..","..skill_names_table[2]..","..skill_names_table[3])
    end
end

