---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by knia.
--- DateTime: 2019/4/12 18:02
---

--获得英雄名字中英文翻译表
require("xml.xml_roleskin")

function getNameFromPath(str)
    local pattern = "%a[_%a]+"
    local res
    for i, v in string.gmatch(str,pattern) do
        res = i
    end
    return string.gsub(res,'/','')
end

function getHeadPicFileName(str)
    local pattern = "%w+_pic_%w*.png"
    return string.match(str,pattern)
end

function getTranslationTable()
    local skininfo = XML_roleskin.heroskin
    local translation = {}
    local heronames = {}
    for i, v in pairs(cfgControlHero:getAllHeroIds()) do
        heronames[i] = { name = cfgControlHero:getName(v) }
        heronames[i].skinid = cfgControlHero:conf(v).skinid
    end
    for i, v in pairs(heronames) do
        translation[v.name] ={
            ["eng"] = getNameFromPath(skininfo[v.skinid].battlemodel),
            ["chn"] = v.name,
            ["head"] = getHeadPicFileName(skininfo[v.skinid].headpic)
        }
    end
    return translation
end
