---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by knia.
--- DateTime: 2019/3/2 20:24
---
require("getExEquipSkills")
require("GetComboList")
require("getHeroData")
require("getSkillDesc")
require("getHeroDialog")
--获取组合技列表
--GetComboList.runGetCombo()

--获取刻印特技列表(excel用)
--GetExEquipSkills.run()

--获得英雄数据
--print(formatTable(cfgControlHero:getHeroBaseInfoAll()))

--获得指定技能描述
--全部
--printAllSkillsDesc()
--指定英雄全部技能
--print(FormatTable(getllAllSkillDesc(10022)))
--指定技能名称
--printSingleSkillDesc("痛苦之力")

--获取全部英雄突破材料、限定、获取方式信息
--print(formatTable(cfgControlSurmount:getAllHerosMoreInfo()))

--获取全部英雄刻印特技（已出特技的），table格式
--print(formatTable(GetExEquipSkills.getAllHeroExEqSkills()))
----获取全部英雄刻印
--print(formatTable(GetExEquipSkills.getAllExEquipWithNames()))

--获取英雄对话和英雄故事
--print(formatTable(getHeroDialogs()))
--print(formatTable(getHeroStories()))

