---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by knia.
--- DateTime: 2019/3/8 18:42
---Description: 工具类
---
--获取table长度
function table_leng(t)
    local leng=0
    for k, v in pairs(t) do
        leng=leng+1
    end
    return leng;
end

--table升序排列
function table_arrange(t)
    local keyTest ={}
    for i in pairs(t) do
        table.insert(keyTest,i)
    end
    table.sort(keyTest,function(a,b)return (tonumber(a) <  tonumber(b)) end)
    local result = { }
    for i,v in pairs(keyTest) do
        table.insert(result,t[v])
    end
    return result
end

--清除html标签
function removeHtmlMark(str)
    str = string.gsub(str, '<script[%a%A]->[%a%A]-</script>', '')
    str = string.gsub(str, '<style[%a%A]->[%a%A]-</style>', '')
    str = string.gsub(str, '<[%a%A]->', '')
    return str
end

--字符串转table
function StrToTable(str)
    if str == nil or type(str) ~= "string" then
        return
    end
    return loadstring("return " .. str)()
end